# Generated by Django 4.2.7 on 2023-12-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='coursecode',
            new_name='courseFee',
        ),
    ]
