# Generated by Django 4.2.7 on 2023-12-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stufee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('Course', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=100)),
                ('Fees', models.CharField(max_length=100)),
            ],
        ),
    ]
